name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  claude-code:
    # Only run when authorized users mention @claude
    if: |
      (
        contains(github.event.comment.body, '@claude') || 
        contains(github.event.issue.body, '@claude') || 
        contains(github.event.pull_request.body, '@claude') ||
        contains(github.event.review.body, '@claude')
      ) &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.issue.author_association == 'OWNER' ||
        github.event.issue.author_association == 'COLLABORATOR' ||
        github.event.issue.author_association == 'MEMBER' ||
        github.event.pull_request.author_association == 'OWNER' ||
        github.event.pull_request.author_association == 'COLLABORATOR' ||
        github.event.pull_request.author_association == 'MEMBER' ||
        github.event.review.author_association == 'OWNER' ||
        github.event.review.author_association == 'COLLABORATOR' ||
        github.event.review.author_association == 'MEMBER'
      )
    runs-on: ubuntu-latest
    
    steps:
      - uses: <YOUR_GITHUB_USERNAME>/claude-code-action@main
        with:
          provider: oauth
          oauth-access-token: ${{ secrets.CLAUDE_ACCESS_TOKEN }}
          oauth-refresh-token: ${{ secrets.CLAUDE_REFRESH_TOKEN }}
          oauth-expires-at: ${{ secrets.CLAUDE_EXPIRES_AT }}